
const exerciseCards=[
['prompt','1 | promptowanie','Dobry i zły prompt','Uczestnicy poprawiają słabe polecenie.','lepszy prompt'],
['text','2 | redakcja','Popraw tekst urzędowy','Uczestnicy upraszczają tekst bez utraty sensu.','jaśniejszy tekst'],
['info','3 | komunikacja','Informacja o szkoleniu','Prompt do komunikatu lub maila.','prompt komunikacyjny'],
['test','4 | edukacja','Test wiedzy','Prompt do testu po szkoleniu.','schemat testu'],
['verify','5 | weryfikacja','Sprawdź odpowiedź AI','Krytyczna ocena wyniku AI.','lista poprawek'],
['own','6 | wdrożenie','Własny prompt do pracy','Prompt do realnego zadania uczestnika.','prompt do pracy'],
['summary','7 | dokumenty','Streszczenie materiału','Prompt do pracy z dłuższym tekstem.','streszczenie i wnioski'],
['workshop','8 | warsztat','Zaprojektuj ćwiczenie','Prompt do aktywności szkoleniowej.','pomysł na ćwiczenie'],
['visual','9 | wizualizacja','Zamień tekst w schemat','Opis procesu do Napkin AI.','struktura procesu'],
['forms','10 | ankieta','Przygotuj ankietę szkoleniową','Ćwiczenie z niespodzianką: szybsze tworzenie formularza.','prompt do ankiety'],
['meeting','11 | biuro','Uporządkuj notatkę ze spotkania','Chaotyczne ustalenia w notatkę i zadania.','tabela zadań'],
['email','12 | komunikacja','Odpowiedz na trudnego maila','Spokojna odpowiedź na wymagającą wiadomość.','bezpieczna odpowiedź']
];

const tools=[
['tekst','ChatGPT','Teksty, prompty, ćwiczenia, scenariusze.','https://chatgpt.com'],
['asystent','Claude','Analiza, pisanie i porządkowanie informacji.','https://claude.ai'],
['dokumenty','NotebookLM','Analiza PDF, notatek i prezentacji.','https://notebooklm.google.com'],
['wizualizacje','Napkin AI','Schematy i mapy myśli z tekstu.','https://www.napkin.ai'],
['wideo','Synthesia','Filmy z awatarem AI.','https://www.synthesia.io'],
['audio','ElevenLabs','Głos AI i nagrania lektorskie.','https://elevenlabs.io'],
['grafika','Canva','Prezentacje, grafiki i materiały.','https://www.canva.com'],
['tłumaczenia','DeepL','Tłumaczenie tekstów i dokumentów.','https://www.deepl.com/pl/translator'],
['kod','Codex','Pomoc w pisaniu i analizie kodu.','https://chatgpt.com/codex'],
['automatyzacja','Google Apps Script','Automatyzacje i integracje Google.','https://script.google.com/'],
['wyszukiwanie','Perplexity','Wyszukiwanie informacji ze źródłami.','https://www.perplexity.ai'],
['prezentacje','Gamma','Szkice prezentacji i materiałów wizualnych.','https://gamma.app']
];

const baseExamples={
prompt:[
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Napisz coś o szkoleniu z AI.','Dodaj odbiorcę, cel, kontekst, format, styl, długość i miejsce publikacji.','Dobry prompt mówi dokładnie, co AI ma przygotować i dla kogo.','Przygotuj krótką informację dla pracowników WUP/PUP o szkoleniu z praktycznego wykorzystania AI. Tekst ma być profesjonalny, prosty i mieć maksymalnie 1000 znaków.','poprawiony prompt','Zapytaj, które doprecyzowanie najbardziej poprawia wynik.'],
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Zrób maila do uczestników.','Doprecyzuj adresatów, temat maila, cel, ton i elementy obowiązkowe.','Mail powinien mieć temat, zwrot, treść i zakończenie.','Przygotuj wiadomość e-mail do uczestników szkolenia z AI. Poinformuj o formule warsztatowej, pracy na przykładach i materiałach w folderze. Styl uprzejmy i profesjonalny.','poprawiony prompt','Sprawdźcie, czy mail nadaje się do wysłania bez dopisków.'],
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Napisz opis do prezentacji.','Podaj temat, odbiorców, długość, styl i zastosowanie opisu.','Opis powinien być konkretny i zgodny z przeznaczeniem.','Przygotuj krótki opis prezentacji o praktycznym wykorzystaniu AI w pracy administracyjnej. Tekst ma mieć 600 znaków i być zrozumiały dla osób początkujących.','poprawiony prompt','Omów, czy opis ma być informacyjny, promocyjny czy sprawozdawczy.'],
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Zrób plan szkolenia.','Określ czas trwania, grupę, cel, poziom uczestników i formę pracy.','Plan powinien być możliwy do przeprowadzenia w realnym czasie.','Przygotuj plan 4-godzinnego warsztatu dla 10 pracowników instytucji publicznej na temat praktycznego wykorzystania AI. Uwzględnij cele, moduły, ćwiczenia i krótkie podsumowanie.','poprawiony prompt','Zwróć uwagę, czy AI nie zaplanowała zbyt wielu elementów.'],
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Napisz regulamin korzystania z AI.','Doprecyzuj, dla kogo jest regulamin, czego dotyczy i jaki ma mieć poziom szczegółowości.','Prompt powinien ograniczać AI, żeby nie tworzyła niepotwierdzonych zasad prawnych.','Przygotuj projekt krótkich zasad bezpiecznego korzystania z AI w pracy biurowej. Tekst ma mieć charakter edukacyjny, nie prawny. Nie dodawaj przepisów, jeśli nie są podane w materiale źródłowym.','poprawiony prompt','Omów różnicę między zasadami edukacyjnymi a dokumentem prawnym.'],
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Zrób podsumowanie projektu.','Podaj źródło danych, odbiorcę, format, zakres i zakaz dopowiadania faktów.','Podsumowanie musi wynikać z danych wejściowych.','Na podstawie poniższych informacji przygotuj krótkie podsumowanie projektu dla kadry zarządzającej. Użyj prostego, profesjonalnego języka. Nie dodawaj informacji spoza materiału.','poprawiony prompt','Sprawdźcie, czy AI nie dopisała efektów projektu.']
],
text:[
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','Informujemy, że w związku z realizacją szkolenia z zakresu sztucznej inteligencji uczestnicy są zobowiązani do zapoznania się z materiałami udostępnionymi w folderze, a także do aktywnego uczestnictwa w zajęciach, ponieważ szkolenie ma na celu podniesienie kompetencji cyfrowych.','Usuń nadmiarowe słowa i zamień „ma na celu” na prostszą konstrukcję.','Tekst powinien być krótszy, jasny i nadal profesjonalny.','Prosimy uczestników szkolenia z zakresu sztucznej inteligencji o zapoznanie się z materiałami udostępnionymi w folderze oraz aktywny udział w zajęciach. Szkolenie pomoże rozwinąć praktyczne kompetencje cyfrowe potrzebne w codziennej pracy.','poprawiony tekst','Pokaż, że formalny tekst nie musi być ciężki.'],
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','W przypadku wystąpienia potrzeby uzyskania dodatkowych informacji dotyczących organizacji szkolenia, uczestnicy mogą kontaktować się z osobą odpowiedzialną za realizację przedmiotowego działania.','Usuń ciężkie konstrukcje i nazwij sprawę prościej.','Tekst ma zachować sens i brzmieć naturalniej.','W sprawach organizacyjnych dotyczących szkolenia uczestnicy mogą kontaktować się z osobą odpowiedzialną za jego realizację.','poprawiony tekst','Wskażcie słowa, które nic nie wnosiły.'],
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','Materiały szkoleniowe zostały przygotowane w celu zapewnienia uczestnikom możliwości samodzielnego utrwalenia wiedzy po zakończeniu zajęć.','Zastąp stronę bierną i rzeczowniki odczasownikowe prostszą składnią.','Tekst powinien być krótki i naturalny.','Materiały szkoleniowe pomagają uczestnikom samodzielnie utrwalić wiedzę po zakończeniu zajęć.','poprawiony tekst','Pokaż, że czasem najlepsza redakcja to odjęcie słów.'],
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','Uczestnictwo w przedmiotowym szkoleniu przyczyni się do zwiększenia poziomu wiedzy w zakresie możliwości wykorzystywania narzędzi sztucznej inteligencji w wykonywaniu zadań zawodowych.','Usuń „przedmiotowe” i uprość rzeczowniki odczasownikowe.','Tekst ma być prosty, ale nadal urzędowy.','Udział w szkoleniu pomoże uczestnikom lepiej wykorzystywać narzędzia sztucznej inteligencji w codziennej pracy.','poprawiony tekst','Porównajcie długość i czytelność obu wersji.'],
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','W celu zapewnienia właściwej organizacji wydarzenia prosimy o dokonanie potwierdzenia uczestnictwa za pośrednictwem formularza zgłoszeniowego.','Zamień „dokonanie potwierdzenia” na czasownik i skróć początek zdania.','Tekst powinien jasno mówić, co trzeba zrobić.','Aby ułatwić organizację wydarzenia, prosimy o potwierdzenie udziału przez formularz zgłoszeniowy.','poprawiony tekst','Zwróć uwagę na czasowniki zamiast rzeczowników.'],
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','Po zakończeniu procesu rekrutacji do uczestników zostanie skierowana informacja dotycząca zakwalifikowania do udziału w szkoleniu.','Uprość stronę bierną i nazwij działanie bezpośrednio.','Tekst ma być komunikacyjny i zrozumiały.','Po zakończeniu rekrutacji poinformujemy uczestników o zakwalifikowaniu do udziału w szkoleniu.','poprawiony tekst','Omówcie, czy wersja aktywna brzmi lepiej.']
]
};

const fallback={
info:['Ćwiczenie: Informacja o szkoleniu','Przygotujcie prompt','Przygotujcie prompt, który pozwoli AI napisać krótką informację o szkoleniu z AI dla pracowników WUP/PUP.','Podaj odbiorcę, miejsce publikacji, styl, długość i cel.','Prompt powinien zawierać konkretne ograniczenia.','Przygotuj krótką informację dla pracowników WUP/PUP o szkoleniu „Nowe kompetencje cyfrowe w praktyce”. Tekst ma być prosty, konkretny, bez języka reklamowego i mieć maksymalnie 1000 znaków.','prompt komunikacyjny','Sprawdźcie, czy tekst pasuje do komunikacji wewnętrznej.'],
test:['Ćwiczenie: Test wiedzy','Stwórzcie prompt do testu','Przygotujcie prompt do testu wiedzy po szkoleniu z AI.','Ustalcie liczbę pytań, typy pytań, poziom i klucz odpowiedzi.','Pytania muszą być jednoznaczne.','Przygotuj test wiedzy po szkoleniu z AI. Test ma zawierać 15 pytań: 9 jednokrotnego wyboru, 3 prawda/fałsz i 3 sytuacyjne. Podaj poprawne odpowiedzi. Próg zaliczenia: 80%.','prompt do testu','Sprawdźcie, czy pytania badają rozumienie.'],
verify:['Ćwiczenie: Sprawdź odpowiedź AI','Oceńcie odpowiedź AI','Wygenerujcie odpowiedź AI i wskażcie, co jest dobre, zbyt ogólne lub wymaga sprawdzenia.','Sprawdźcie daty, liczby, źródła, ton i zgodność z poleceniem.','AI może pisać płynnie, ale nadal może się mylić.','Sprawdź poniższą odpowiedź AI. Wskaż elementy poprawne, informacje wymagające weryfikacji, fragmenty zbyt ogólne, błędy i propozycję poprawy.','lista poprawek','Podkreśl, że ładna forma nie oznacza poprawności.'],
own:['Ćwiczenie: Własny prompt do pracy','Zbudujcie własny prompt','Wybierzcie jedno realne zadanie ze swojej pracy i przygotujcie do niego prompt.','Uwzględnijcie rolę AI, zadanie, kontekst, odbiorcę, styl, format i ograniczenia.','Prompt powinien nadawać się do ponownego użycia.','Jesteś redaktorem pracującym dla instytucji publicznej. Pomóż mi przygotować profesjonalny tekst na podstawie poniższych informacji. Zachowaj sens i nie dodawaj niepotwierdzonych danych.','własny prompt','Poproś uczestników, żeby zapisali prompt po szkoleniu.'],
summary:['Ćwiczenie: Streszczenie materiału','Przygotujcie prompt do streszczenia','Przygotujcie prompt, który pozwoli AI streścić dokument albo prezentację i wypisać najważniejsze wnioski.','Określcie format, liczbę punktów, odbiorcę i poziom szczegółowości.','AI nie może dodawać faktów spoza tekstu.','Przygotuj streszczenie poniższego materiału w 6 punktach. Następnie wypisz 3 najważniejsze wnioski i 3 pytania do omówienia.','prompt do streszczenia','Omówcie, jak sprawdzić kompletność streszczenia.'],
workshop:['Ćwiczenie: Zaprojektuj ćwiczenie','Zaprojektujcie ćwiczenie','Przygotujcie prompt, który pozwoli AI stworzyć krótkie ćwiczenie warsztatowe.','Określcie temat, czas, liczbę uczestników, cel, przebieg i pytania.','Ćwiczenie musi być wykonalne i praktyczne.','Przygotuj 15-minutowe ćwiczenie warsztatowe dla grupy 10 osób na temat bezpiecznego korzystania z AI w pracy administracyjnej.','pomysł na ćwiczenie','Sprawdźcie, czy ćwiczenie da się wykonać w czasie.'],
visual:['Ćwiczenie: Zamień tekst w schemat','Przygotujcie opis do wizualizacji','Wybierzcie proces i przygotujcie prompt do schematu lub mapy myśli.','Nazwijcie proces, kroki, decyzje, osoby i efekt końcowy.','Opis ma być krótki i logiczny.','Zamień poniższy opis procesu w prosty schemat krok po kroku. Wskaż etapy, osoby odpowiedzialne, decyzje i efekt końcowy.','opis do wizualizacji','Omówcie, czy schemat pokazuje proces.'],
forms:['Ćwiczenie: Przygotuj ankietę','Przygotujcie ankietę po szkoleniu','Przygotujcie prompt, który pomoże stworzyć ankietę ewaluacyjną po szkoleniu.','Podajcie temat, pytania, skalę ocen i pytania otwarte.','Dobry prompt może poprosić też o kod formularza.','Przygotuj kod Google Apps Script, który automatycznie utworzy formularz Google Forms do ewaluacji szkolenia. Formularz ma zawierać imię i nazwisko, 8 pytań w skali 1-5 i 3 pytania otwarte.','prompt do ankiety','To moment „wow”: nie tylko pytania, ale formularz.'],
meeting:['Ćwiczenie: Uporządkuj notatkę','Uporządkujcie notatkę','Przygotujcie prompt, który zamieni notatki ze spotkania w podsumowanie, ustalenia, tabelę zadań i pytania otwarte.','Dodajcie zakaz dopisywania informacji.','Dobry wynik oddziela fakty od braków.','Uporządkuj poniższe notatki. Przygotuj podsumowanie, listę ustaleń, tabelę zadań i listę spraw do doprecyzowania.','notatka i tabela','Podkreśl różnicę między porządkowaniem a dopowiadaniem.'],
email:['Ćwiczenie: Odpowiedz na trudnego maila','Przygotujcie odpowiedź','Przygotujcie prompt, który pomoże napisać spokojną odpowiedź na wymagającą wiadomość.','Nie przyznawajcie racji ani winy, jeśli nie wynika to z treści.','Odpowiedź ma być spokojna, konkretna i bezpieczna.','Przygotuj uprzejmą odpowiedź na poniższą wiadomość. Ton ma być spokojny i rzeczowy. Nie przyznawaj racji ani winy, jeśli nie wynika to z treści.','odpowiedź mailowa','Omówcie, co obniża napięcie w komunikacji.']
};

let currentExerciseType='prompt';
function esc(s){return String(s).replace(/[&<>'"]/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m];});}
function init(){
  document.getElementById('exerciseCards').innerHTML=exerciseCards.map(function(c){return '<article class="card"><span class="tag">'+esc(c[1])+'</span><h3>'+esc(c[2])+'</h3><p>'+esc(c[3])+'</p><p class="small"><strong>Efekt:</strong> '+esc(c[4])+'</p><button class="btn" onclick="openExercise(\''+c[0]+'\')">Uruchom</button></article>';}).join('');
  document.getElementById('toolCards').innerHTML=tools.map(function(t){return '<article class="card"><span class="tag">'+esc(t[0])+'</span><h3>'+esc(t[1])+'</h3><p>'+esc(t[2])+'</p><a class="btn" target="_blank" href="'+esc(t[3])+'">Otwórz</a></article>';}).join('');
}
function pickExercise(type){var list=baseExamples[type];if(list){return list[Math.floor(Math.random()*list.length)];}return fallback[type]||baseExamples.prompt[0];}
function renderExercise(e){document.getElementById('exTitle').textContent=e[0];document.getElementById('exHeading').textContent=e[1];document.getElementById('exTask').textContent=e[2];document.getElementById('exHint').textContent=e[3];document.getElementById('exCheck').textContent=e[4];document.getElementById('exSample').textContent=e[5];document.getElementById('exResult').textContent=e[6];document.getElementById('exDiscuss').textContent=e[7]||'Porównajcie wynik pracy z przykładem i wskażcie, co można poprawić.';['exHint','exCheck','exSample','exDiscuss'].forEach(function(id){document.getElementById(id).classList.remove('active');});document.getElementById('exWork').value='';}
function openExercise(type){currentExerciseType=type;renderExercise(pickExercise(type));document.getElementById('exerciseOverlay').classList.add('active');}
function randomizeCurrentExercise(){renderExercise(pickExercise(currentExerciseType));}
function closeExercise(){document.getElementById('exerciseOverlay').classList.remove('active');}
function toggle(id){document.getElementById(id).classList.toggle('active');}
function qrGenerate(){var v=document.getElementById('qrInput').value.trim();if(!v){alert('Wklej link.');return;}try{new URL(v);}catch(e){alert('Wklej poprawny link zaczynający się od https:// albo http://');return;}var src='https://api.qrserver.com/v1/create-qr-code/?size=360x360&data='+encodeURIComponent(v);document.getElementById('qrBox').innerHTML='<img src="'+src+'" alt="QR">';document.getElementById('qrText').textContent=v;}
function qrClear(){document.getElementById('qrInput').value='';document.getElementById('qrBox').textContent='Tutaj pojawi się kod QR';document.getElementById('qrText').textContent='';}
function qrBig(){var v=document.getElementById('qrInput').value.trim();if(!v){alert('Najpierw wklej link i wygeneruj QR.');return;}try{new URL(v);}catch(e){alert('Wklej poprawny link zaczynający się od https:// albo http://');return;}var src='https://api.qrserver.com/v1/create-qr-code/?size=900x900&data='+encodeURIComponent(v);document.getElementById('qrFullImg').innerHTML='<img src="'+src+'" alt="QR">';document.getElementById('qrFullText').textContent=v;document.getElementById('qrFull').classList.add('active');}
function closeQrBig(){document.getElementById('qrFull').classList.remove('active');}
document.addEventListener('keydown',function(e){if(e.key==='Escape'){closeExercise();closeQrBig();}});
init();
