
const exerciseCards=[
['prompt','1 | promptowanie','Dobry i zły prompt','Uczestnicy poprawiają słabe polecenie.','lepszy prompt'],
['text','2 | redakcja','Popraw tekst urzędowy','Uczestnicy upraszczają tekst bez utraty sensu.','jaśniejszy tekst'],
['info','3 | komunikacja','Informacja o szkoleniu','Prompt do komunikatu lub maila.','prompt komunikacyjny'],
['test','4 | edukacja','Test wiedzy','Prompt do testu po szkoleniu.','schemat testu'],
['verify','5 | weryfikacja','Sprawdź odpowiedź AI','Krytyczna ocena wyniku AI.','lista poprawek'],
['own','6 | wdrożenie','Własny prompt do pracy','Prompt do realnego zadania uczestnika.','prompt do pracy'],
['summary','7 | dokumenty','Streszczenie materiału','Prompt do pracy z dłuższym tekstem.','streszczenie i wnioski'],
['workshop','8 | warsztat','Zaprojektuj ćwiczenie','Prompt do aktywności szkoleniowej.','pomysł na ćwiczenie'],
['visual','9 | wizualizacja','Zamień tekst w schemat','Opis procesu do Napkin AI.','struktura procesu'],
['forms','10 | ankieta','Przygotuj ankietę szkoleniową','Ćwiczenie z niespodzianką: szybsze tworzenie formularza.','prompt do ankiety'],
['meeting','11 | biuro','Uporządkuj notatkę ze spotkania','Chaotyczne ustalenia w notatkę i zadania.','tabela zadań'],
['email','12 | komunikacja','Odpowiedz na trudnego maila','Spokojna odpowiedź na wymagającą wiadomość.','bezpieczna odpowiedź']
];

const tools=[
['tekst','ChatGPT','Teksty, prompty, ćwiczenia, scenariusze.','https://chatgpt.com'],
['asystent','Claude','Analiza, pisanie i porządkowanie informacji.','https://claude.ai'],
['dokumenty','NotebookLM','Analiza PDF, notatek i prezentacji.','https://notebooklm.google.com'],
['wizualizacje','Napkin AI','Schematy i mapy myśli z tekstu.','https://www.napkin.ai'],
['wideo','Synthesia','Filmy z awatarem AI.','https://www.synthesia.io'],
['audio','ElevenLabs','Głos AI i nagrania lektorskie.','https://elevenlabs.io'],
['grafika','Canva','Prezentacje, grafiki i materiały.','https://www.canva.com'],
['tłumaczenia','DeepL','Tłumaczenie tekstów i dokumentów.','https://www.deepl.com/pl/translator'],
['kod','Codex','Pomoc w pisaniu i analizie kodu.','https://chatgpt.com/codex'],
['automatyzacja','Google Apps Script','Automatyzacje i integracje Google.','https://script.google.com/'],
['wyszukiwanie','Perplexity','Wyszukiwanie informacji ze źródłami.','https://www.perplexity.ai'],
['prezentacje','Gamma','Szkice prezentacji i materiałów wizualnych.','https://gamma.app']
];

const exercises={
prompt:[
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Słaby prompt: „Napisz coś o szkoleniu z AI.”','Dodaj odbiorcę, cel, kontekst, format, styl, długość i miejsce publikacji.','Dobry prompt mówi dokładnie, co AI ma przygotować i dla kogo.','Przygotuj krótką informację dla pracowników WUP/PUP o szkoleniu z praktycznego wykorzystania AI. Tekst ma być profesjonalny, prosty i mieć maksymalnie 1000 znaków.','poprawiony prompt','Zapytaj, które doprecyzowanie najbardziej poprawia wynik.'],
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Słaby prompt: „Zrób maila do uczestników.”','Doprecyzuj adresatów, temat maila, cel, ton i elementy obowiązkowe.','Mail powinien mieć temat, zwrot, treść i zakończenie.','Przygotuj wiadomość e-mail do uczestników szkolenia z AI. Poinformuj o formule warsztatowej, pracy na przykładach i materiałach w folderze. Styl uprzejmy i profesjonalny.','poprawiony prompt','Sprawdźcie, czy mail nadaje się do wysłania bez dopisków.'],
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Słaby prompt: „Napisz opis do prezentacji.”','Podaj temat, odbiorców, długość, styl i zastosowanie opisu.','Opis powinien być konkretny i zgodny z przeznaczeniem.','Przygotuj krótki opis prezentacji o praktycznym wykorzystaniu AI w pracy administracyjnej. Tekst ma mieć 600 znaków i być zrozumiały dla osób początkujących.','poprawiony prompt','Omów, czy opis ma być informacyjny, promocyjny czy sprawozdawczy.'],
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Słaby prompt: „Zrób plan szkolenia.”','Określ czas trwania, grupę, cel, poziom uczestników i formę pracy.','Plan powinien być możliwy do przeprowadzenia w realnym czasie.','Przygotuj plan 4-godzinnego warsztatu dla 10 pracowników instytucji publicznej na temat praktycznego wykorzystania AI. Uwzględnij cele, moduły, ćwiczenia i krótkie podsumowanie.','poprawiony prompt','Zwróć uwagę, czy AI nie zaplanowała zbyt wielu elementów.'],
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Słaby prompt: „Napisz regulamin korzystania z AI.”','Doprecyzuj, dla kogo jest regulamin, czego dotyczy i jaki ma mieć poziom szczegółowości.','Prompt powinien ograniczać AI, żeby nie tworzyła niepotwierdzonych zasad prawnych.','Przygotuj projekt krótkich zasad bezpiecznego korzystania z AI w pracy biurowej. Tekst ma mieć charakter edukacyjny, nie prawny. Nie dodawaj przepisów, jeśli nie są podane w materiale źródłowym.','poprawiony prompt','Omów różnicę między zasadami edukacyjnymi a dokumentem prawnym.'],
['Ćwiczenie: Dobry i zły prompt','Poprawcie prompt','Słaby prompt: „Zrób podsumowanie projektu.”','Podaj źródło danych, odbiorcę, format, zakres i zakaz dopowiadania faktów.','Podsumowanie musi wynikać z danych wejściowych.','Na podstawie poniższych informacji przygotuj krótkie podsumowanie projektu dla kadry zarządzającej. Użyj prostego, profesjonalnego języka. Nie dodawaj informacji spoza materiału.','poprawiony prompt','Sprawdźcie, czy AI nie dopisała efektów projektu.']
],
text:[
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','Informujemy, że w związku z realizacją szkolenia z zakresu sztucznej inteligencji uczestnicy są zobowiązani do zapoznania się z materiałami udostępnionymi w folderze, a także do aktywnego uczestnictwa w zajęciach, ponieważ szkolenie ma na celu podniesienie kompetencji cyfrowych.','Usuń nadmiarowe słowa i zamień „ma na celu” na prostszą konstrukcję.','Tekst powinien być krótszy, jasny i nadal profesjonalny.','Prosimy uczestników szkolenia z zakresu sztucznej inteligencji o zapoznanie się z materiałami udostępnionymi w folderze oraz aktywny udział w zajęciach. Szkolenie pomoże rozwinąć praktyczne kompetencje cyfrowe potrzebne w codziennej pracy.','poprawiony tekst','Pokaż, że formalny tekst nie musi być ciężki.'],
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','W przypadku wystąpienia potrzeby uzyskania dodatkowych informacji dotyczących organizacji szkolenia, uczestnicy mogą kontaktować się z osobą odpowiedzialną za realizację przedmiotowego działania.','Usuń ciężkie konstrukcje i nazwij sprawę prościej.','Tekst ma zachować sens i brzmieć naturalniej.','W sprawach organizacyjnych dotyczących szkolenia uczestnicy mogą kontaktować się z osobą odpowiedzialną za jego realizację.','poprawiony tekst','Wskażcie słowa, które nic nie wnosiły.'],
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','Materiały szkoleniowe zostały przygotowane w celu zapewnienia uczestnikom możliwości samodzielnego utrwalenia wiedzy po zakończeniu zajęć.','Zastąp stronę bierną i rzeczowniki odczasownikowe prostszą składnią.','Tekst powinien być krótki i naturalny.','Materiały szkoleniowe pomagają uczestnikom samodzielnie utrwalić wiedzę po zakończeniu zajęć.','poprawiony tekst','Pokaż, że czasem najlepsza redakcja to odjęcie słów.'],
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','Uczestnictwo w przedmiotowym szkoleniu przyczyni się do zwiększenia poziomu wiedzy w zakresie możliwości wykorzystywania narzędzi sztucznej inteligencji w wykonywaniu zadań zawodowych.','Usuń „przedmiotowe” i uprość rzeczowniki odczasownikowe.','Tekst ma być prosty, ale nadal urzędowy.','Udział w szkoleniu pomoże uczestnikom lepiej wykorzystywać narzędzia sztucznej inteligencji w codziennej pracy.','poprawiony tekst','Porównajcie długość i czytelność obu wersji.'],
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','W celu zapewnienia właściwej organizacji wydarzenia prosimy o dokonanie potwierdzenia uczestnictwa za pośrednictwem formularza zgłoszeniowego.','Zamień „dokonanie potwierdzenia” na czasownik i skróć początek zdania.','Tekst powinien jasno mówić, co trzeba zrobić.','Aby ułatwić organizację wydarzenia, prosimy o potwierdzenie udziału przez formularz zgłoszeniowy.','poprawiony tekst','Zwróć uwagę na czasowniki zamiast rzeczowników.'],
['Ćwiczenie: Popraw tekst urzędowy','Poprawcie tekst','Po zakończeniu procesu rekrutacji do uczestników zostanie skierowana informacja dotycząca zakwalifikowania do udziału w szkoleniu.','Uprość stronę bierną i nazwij działanie bezpośrednio.','Tekst ma być komunikacyjny i zrozumiały.','Po zakończeniu rekrutacji poinformujemy uczestników o zakwalifikowaniu do udziału w szkoleniu.','poprawiony tekst','Omówcie, czy wersja aktywna brzmi lepiej.']
],
info:[
['Ćwiczenie: Informacja o szkoleniu','Przygotujcie prompt','Przygotuj prompt do informacji dla pracowników WUP/PUP o szkoleniu z AI.','Podaj odbiorcę, miejsce publikacji, styl, długość i cel.','Prompt powinien zawierać konkretne ograniczenia.','Przygotuj krótką informację dla pracowników WUP/PUP o szkoleniu „Nowe kompetencje cyfrowe w praktyce”. Tekst ma być prosty, konkretny, bez języka reklamowego i mieć maksymalnie 1000 znaków.','prompt komunikacyjny','Sprawdźcie, czy tekst pasuje do komunikacji wewnętrznej.'],
['Ćwiczenie: Informacja o szkoleniu','Przygotujcie prompt','Przygotuj prompt do zaproszenia pracowników na szkolenie z AI.','Wskaż kto zaprasza, kogo, po co i jaki ma być ton.','Zaproszenie nie powinno być reklamą.','Przygotuj zaproszenie dla pracowników WUP/PUP na warsztatowe szkolenie z praktycznego wykorzystania AI. Styl uprzejmy, konkretny i profesjonalny.','prompt do zaproszenia','Omówcie, czy zaproszenie jest zachęcające, ale nie przesadne.'],
['Ćwiczenie: Informacja o szkoleniu','Przygotujcie prompt','Przygotuj prompt do krótkiej informacji po zakończeniu szkolenia.','Uwzględnij efekty, przebieg i neutralny styl sprawozdawczy.','Tekst powinien być gotowy do publikacji.','Przygotuj krótką informację po zakończeniu szkolenia z AI. Opisz temat, charakter warsztatowy, wykonane ćwiczenia i możliwe zastosowanie wiedzy w pracy.','prompt sprawozdawczy','Sprawdźcie, czy AI nie dodaje nieprawdziwych liczb.'],
['Ćwiczenie: Informacja o szkoleniu','Przygotujcie prompt','Przygotuj prompt do komunikatu przypominającego o szkoleniu.','Podaj termin, materiały, przygotowanie uczestników i ton wiadomości.','Komunikat ma być krótki i praktyczny.','Przygotuj krótkie przypomnienie dla uczestników szkolenia z AI. Uwzględnij prośbę o zapoznanie się z materiałami, punktualność i warsztatowy charakter zajęć.','prompt do przypomnienia','Omówcie, czy treść nie jest zbyt długa.'],
['Ćwiczenie: Informacja o szkoleniu','Przygotujcie prompt','Przygotuj prompt do opisu szkolenia na stronę internetową.','Określ odbiorców, cel, zakres i długość tekstu.','Opis powinien informować, a nie obiecywać zbyt wiele.','Przygotuj opis szkolenia z praktycznego wykorzystania AI na stronę internetową instytucji publicznej. Tekst ma mieć 1200 znaków, być konkretny i zrozumiały.','prompt na stronę','Wskażcie fragmenty, które mogą brzmieć zbyt marketingowo.'],
['Ćwiczenie: Informacja o szkoleniu','Przygotujcie prompt','Przygotuj prompt do krótkiego wpisu na LinkedIn o szkoleniu.','Podaj odbiorcę, ton, długość i zakaz przesadnego języka.','Wpis powinien być profesjonalny i naturalny.','Przygotuj krótki wpis na LinkedIn o szkoleniu z praktycznego wykorzystania AI w pracy instytucji publicznej. Styl profesjonalny, rzeczowy, bez przesady marketingowej.','prompt do social media','Omówcie, jak uniknąć sztucznego entuzjazmu.']
],
test:[
['Ćwiczenie: Test wiedzy','Stwórzcie prompt do testu','Przygotuj prompt do testu wiedzy po szkoleniu z AI.','Ustal liczbę pytań, typy pytań, poziom i klucz odpowiedzi.','Pytania muszą być jednoznaczne.','Przygotuj test wiedzy po szkoleniu z AI. Test ma zawierać 15 pytań: 9 jednokrotnego wyboru, 3 prawda/fałsz i 3 sytuacyjne. Podaj poprawne odpowiedzi. Próg zaliczenia: 80%.','prompt do testu','Sprawdźcie, czy pytania badają rozumienie.'],
['Ćwiczenie: Test wiedzy','Stwórzcie prompt do quizu','Przygotuj prompt do krótkiego quizu na rozpoczęcie szkolenia.','Quiz ma badać poziom wejściowy, więc pytania powinny być proste.','Quiz nie powinien zawstydzać uczestników.','Przygotuj quiz wstępny z 8 pytaniami o podstawowe zastosowania AI, bezpieczeństwo danych i pisanie promptów. Podaj odpowiedzi.','prompt do quizu','Omówcie, jak wykorzystać wynik quizu.'],
['Ćwiczenie: Test wiedzy','Stwórzcie pytania sytuacyjne','Przygotuj prompt do pytań sytuacyjnych o bezpieczne korzystanie z AI.','Skup się na decyzjach z pracy, nie na definicjach.','Pytania mają sprawdzać zachowanie w praktyce.','Przygotuj 5 pytań sytuacyjnych dotyczących bezpiecznego korzystania z AI w pracy administracyjnej. Podaj najlepszą odpowiedź i krótkie uzasadnienie.','prompt do scenariuszy','Porównajcie pytania sytuacyjne z definicyjnymi.'],
['Ćwiczenie: Test wiedzy','Stwórzcie test po module','Przygotuj prompt do testu po module o promptowaniu.','Zakres testu ma dotyczyć tylko jednego modułu.','Pytania powinny być krótkie i precyzyjne.','Przygotuj 10 pytań po module „Pisanie skutecznych promptów”. Uwzględnij kontekst, odbiorcę, format, ograniczenia i iteracyjne poprawianie poleceń.','prompt modułowy','Sprawdźcie, czy test nie wychodzi poza zakres modułu.'],
['Ćwiczenie: Test wiedzy','Stwórzcie test z progiem zaliczenia','Przygotuj prompt do testu z automatyczną informacją o progu zaliczenia.','Ustal liczbę punktów i próg procentowy.','AI musi podać poprawne odpowiedzi i punktację.','Przygotuj test z 12 pytaniami po szkoleniu z AI. Podaj poprawne odpowiedzi, punktację i informację, że zaliczenie wymaga 80% poprawnych odpowiedzi.','prompt z punktacją','Omówcie, czy próg jest jasno opisany.'],
['Ćwiczenie: Test wiedzy','Stwórzcie pytania do dyskusji','Przygotuj prompt do pytań sprawdzających przez rozmowę, nie przez test.','Pytania mają pobudzać refleksję i omówienie ryzyk.','Nie każde sprawdzenie wiedzy musi być testem.','Przygotuj 8 pytań do dyskusji po szkoleniu z AI. Pytania mają sprawdzać, czy uczestnicy rozumieją zastosowania, ograniczenia i zasady bezpieczeństwa.','prompt do dyskusji','Porównajcie wartość testu i rozmowy.']
],
verify:[
['Ćwiczenie: Sprawdź odpowiedź AI','Oceńcie odpowiedź AI','Wygenerujcie odpowiedź AI i wskażcie, co jest dobre, zbyt ogólne lub wymaga sprawdzenia.','Sprawdźcie daty, liczby, źródła, ton i zgodność z poleceniem.','AI może pisać płynnie, ale nadal może się mylić.','Sprawdź poniższą odpowiedź AI. Wskaż elementy poprawne, informacje wymagające weryfikacji, fragmenty zbyt ogólne, błędy i propozycję poprawy.','lista poprawek','Podkreśl, że ładna forma nie oznacza poprawności.'],
['Ćwiczenie: Sprawdź odpowiedź AI','Oceńcie tekst przed publikacją','Przygotuj prompt do redakcyjnej kontroli tekstu wygenerowanego przez AI.','Szukaj powtórzeń, ogólników i niepotwierdzonych informacji.','Tekst po AI wymaga kontroli człowieka.','Przeanalizuj poniższy tekst przed publikacją. Wskaż fragmenty do skrócenia, uproszczenia, weryfikacji i redakcji językowej.','kontrola tekstu','Omówcie, co można opublikować, a czego nie.'],
['Ćwiczenie: Sprawdź odpowiedź AI','Wykryj ogólniki','Znajdźcie w odpowiedzi AI puste sformułowania i zastąpcie je konkretem.','Szukajcie słów: ważne, kluczowe, nowoczesne, kompleksowe.','Poprawiona wersja powinna być konkretniejsza.','Wskaż w poniższym tekście ogólniki i zastąp je konkretnymi informacjami. Nie dodawaj faktów spoza materiału źródłowego.','konkretyzacja','Pokaż, że ogólniki często ukrywają brak treści.'],
['Ćwiczenie: Sprawdź odpowiedź AI','Sprawdź zgodność z poleceniem','Oceńcie, czy odpowiedź AI rzeczywiście realizuje prompt.','Porównaj zadanie z wynikiem punkt po punkcie.','AI może odpowiedzieć płynnie, ale obok tematu.','Porównaj poniższą odpowiedź z poleceniem. Wskaż, które wymagania zostały spełnione, które pominięte i co trzeba poprawić.','kontrola zgodności','Omówcie, dlaczego warto czytać własny prompt po otrzymaniu odpowiedzi.'],
['Ćwiczenie: Sprawdź odpowiedź AI','Sprawdź ryzyko RODO','Oceńcie odpowiedź AI pod kątem danych osobowych i informacji poufnych.','Zwróć uwagę na dane, identyfikatory, adresy, nazwiska i szczegóły spraw.','Nie każdą treść można wkleić do narzędzia AI.','Przeanalizuj poniższy materiał pod kątem ryzyka ujawnienia danych osobowych lub informacji poufnych. Wskaż, co należy usunąć lub zanonimizować.','kontrola ryzyka','Omówcie zasadę minimalizacji danych.'],
['Ćwiczenie: Sprawdź odpowiedź AI','Sprawdź ton komunikatu','Oceńcie, czy komunikat wygenerowany przez AI ma odpowiedni ton.','Szukaj przesady, sztuczności, zbyt dużej formalności lub zbyt luźnego języka.','Ton musi pasować do odbiorcy i instytucji.','Oceń ton poniższego komunikatu. Wskaż fragmenty zbyt formalne, zbyt marketingowe lub niejasne. Zaproponuj poprawioną wersję.','kontrola tonu','Porównajcie ton urzędowy, informacyjny i promocyjny.']
],
own:[
['Ćwiczenie: Własny prompt do pracy','Zbudujcie własny prompt','Wybierzcie jedno realne zadanie ze swojej pracy i przygotujcie do niego prompt.','Uwzględnijcie rolę AI, zadanie, kontekst, odbiorcę, styl, format i ograniczenia.','Prompt powinien nadawać się do ponownego użycia.','Jesteś redaktorem pracującym dla instytucji publicznej. Pomóż mi przygotować profesjonalny tekst na podstawie poniższych informacji. Zachowaj sens i nie dodawaj niepotwierdzonych danych.','własny prompt','Poproś uczestników, żeby zapisali prompt po szkoleniu.'],
['Ćwiczenie: Własny prompt do pracy','Prompt do maili','Przygotuj prompt do poprawiania własnych wiadomości e-mail.','Określ ton, długość, odbiorcę i zakaz dopisywania faktów.','Prompt powinien działać przy codziennych mailach.','Popraw poniższą wiadomość e-mail tak, aby była uprzejma, konkretna i profesjonalna. Zachowaj sens, nie dodawaj nowych informacji i skróć zbyt długie zdania.','prompt do maili','Omówcie, czy mail nadal brzmi jak Wasz styl.'],
['Ćwiczenie: Własny prompt do pracy','Prompt do streszczania dokumentów','Przygotuj prompt do streszczania dłuższych dokumentów.','Określ format, długość, wnioski i sprawy do działania.','Prompt powinien pomagać w pracy z informacją.','Streść poniższy dokument w 6 punktach. Wypisz decyzje, terminy, osoby odpowiedzialne i sprawy wymagające dalszego działania.','prompt do dokumentów','Wskażcie, jak sprawdzać streszczenie.'],
['Ćwiczenie: Własny prompt do pracy','Prompt do opisu działania','Przygotuj prompt do opisywania działań projektowych.','Określ odbiorcę, styl i zakres informacji.','Opis ma być konkretny i zgodny z realiami projektu.','Na podstawie poniższych informacji przygotuj opis działania projektowego. Użyj języka profesjonalnego, prostego i zgodnego z komunikacją instytucji publicznej.','prompt projektowy','Sprawdźcie, czy AI nie dopisała rezultatów.'],
['Ćwiczenie: Własny prompt do pracy','Prompt do listy zadań','Przygotuj prompt, który zamienia opis sprawy w listę działań.','Określ format tabeli i pola: zadanie, termin, osoba, ryzyko.','Prompt ma pomagać w organizacji pracy.','Zamień poniższy opis sprawy w tabelę z zadaniami, terminami, osobami odpowiedzialnymi i ryzykami. Nie dopisuj informacji, których nie ma w opisie.','prompt organizacyjny','Omówcie, czy tabela jest kompletna.'],
['Ćwiczenie: Własny prompt do pracy','Prompt do upraszczania języka','Przygotuj prompt do prostszego pisania tekstów dla odbiorców zewnętrznych.','Zachowaj sens, ale zmniejsz formalność.','Prompt powinien poprawiać zrozumiałość.','Uprość poniższy tekst tak, aby był zrozumiały dla osoby spoza instytucji. Zachowaj sens, nie usuwaj informacji ważnych formalnie i nie dodawaj nowych danych.','prompt językowy','Porównajcie, co można uprościć, a czego nie.']
],
summary:[
['Ćwiczenie: Streszczenie materiału','Przygotujcie prompt do streszczenia','Przygotuj prompt, który pozwoli AI streścić dokument albo prezentację i wypisać najważniejsze wnioski.','Określ format, liczbę punktów, odbiorcę i poziom szczegółowości.','AI nie może dodawać faktów spoza tekstu.','Przygotuj streszczenie poniższego materiału w 6 punktach. Następnie wypisz 3 najważniejsze wnioski i 3 pytania do omówienia.','prompt do streszczenia','Omówcie, jak sprawdzić kompletność streszczenia.'],
['Ćwiczenie: Streszczenie materiału','Streszczenie dla przełożonego','Przygotuj prompt do streszczenia materiału dla kadry zarządzającej.','Ma być krótko, rzeczowo i z wnioskami.','Streszczenie powinno wspierać decyzję.','Streść poniższy materiał dla osoby decyzyjnej. Podaj: kontekst, 5 wniosków, ryzyka i rekomendację dalszego działania.','prompt decyzyjny','Omówcie, czy streszczenie ma wystarczający poziom konkretu.'],
['Ćwiczenie: Streszczenie materiału','Streszczenie dla uczestników','Przygotuj prompt do prostego podsumowania materiału dla uczestników szkolenia.','Język ma być prosty i edukacyjny.','Streszczenie powinno pomagać w nauce.','Przygotuj podsumowanie materiału dla uczestników szkolenia. Użyj prostego języka, wypisz najważniejsze pojęcia i dodaj 3 pytania sprawdzające.','prompt edukacyjny','Sprawdźcie, czy podsumowanie nie jest zbyt trudne.'],
['Ćwiczenie: Streszczenie materiału','Wyciągnij działania','Przygotuj prompt do wyciągania z dokumentu zadań i terminów.','Format powinien być tabelą.','AI nie może wymyślać terminów.','Z poniższego dokumentu wypisz zadania, terminy, osoby odpowiedzialne i sprawy wymagające decyzji. Jeśli czegoś brakuje, wpisz „brak informacji”.','prompt zadaniowy','Omówcie, jak oznaczać braki informacji.'],
['Ćwiczenie: Streszczenie materiału','Porównaj dwa źródła','Przygotuj prompt do porównania dwóch materiałów.','Wskaż podobieństwa, różnice i sprzeczności.','Porównanie powinno być oparte tylko na źródłach.','Porównaj dwa poniższe materiały. Wskaż wspólne wnioski, różnice, sprzeczności i pytania do dalszego wyjaśnienia.','prompt porównawczy','Sprawdźcie, czy AI nie uśrednia sprzecznych informacji.'],
['Ćwiczenie: Streszczenie materiału','Zrób notatkę do akt','Przygotuj prompt do krótkiej notatki służbowej na podstawie materiału.','Styl ma być rzeczowy i neutralny.','Notatka nie powinna zawierać komentarzy.','Na podstawie poniższego materiału przygotuj krótką notatkę służbową: temat, podstawa informacji, ustalenia, dalsze kroki.','prompt do notatki','Omówcie różnicę między notatką a interpretacją.']
],
workshop:[
['Ćwiczenie: Zaprojektuj ćwiczenie','Zaprojektujcie ćwiczenie','Przygotuj prompt, który pozwoli AI stworzyć krótkie ćwiczenie warsztatowe.','Określ temat, czas, liczbę uczestników, cel, przebieg i pytania.','Ćwiczenie musi być wykonalne i praktyczne.','Przygotuj 15-minutowe ćwiczenie warsztatowe dla grupy 10 osób na temat bezpiecznego korzystania z AI w pracy administracyjnej.','pomysł na ćwiczenie','Sprawdźcie, czy ćwiczenie da się wykonać w czasie.'],
['Ćwiczenie: Zaprojektuj ćwiczenie','Ćwiczenie na start','Przygotuj prompt do aktywności otwierającej szkolenie.','Ma być krótko, lekko i bez stresu.','Ćwiczenie ma aktywizować grupę.','Przygotuj 10-minutowe ćwiczenie otwierające szkolenie z AI dla osób początkujących. Bez dodatkowych materiałów.','icebreaker','Omówcie, czy ćwiczenie nie jest infantylne.'],
['Ćwiczenie: Zaprojektuj ćwiczenie','Ćwiczenie w parach','Przygotuj prompt do pracy w parach.','Zadanie ma mieć jasny rezultat.','Uczestnicy muszą wiedzieć, co oddają na końcu.','Przygotuj ćwiczenie w parach na temat poprawiania promptów. Czas: 12 minut. Efekt: jedna poprawiona wersja promptu.','ćwiczenie w parach','Sprawdźcie, czy instrukcja jest jednoznaczna.'],
['Ćwiczenie: Zaprojektuj ćwiczenie','Ćwiczenie z dyskusją','Przygotuj prompt do ćwiczenia kończącego się dyskusją.','Dodaj pytania do omówienia.','Dyskusja ma prowadzić do wniosków.','Przygotuj ćwiczenie o ryzykach korzystania z AI. Zakończ je 5 pytaniami do dyskusji.','ćwiczenie z dyskusją','Omówcie, czy pytania nie są zbyt ogólne.'],
['Ćwiczenie: Zaprojektuj ćwiczenie','Ćwiczenie z analizą błędu','Przygotuj prompt do ćwiczenia, w którym uczestnicy szukają błędów AI.','Podaj materiał, zadanie i kryteria oceny.','Ćwiczenie ma uczyć krytycznego myślenia.','Przygotuj ćwiczenie, w którym uczestnicy analizują odpowiedź AI i wskazują błędy, ogólniki oraz informacje do sprawdzenia.','ćwiczenie analityczne','Podkreśl, że AI trzeba sprawdzać.'],
['Ćwiczenie: Zaprojektuj ćwiczenie','Ćwiczenie wdrożeniowe','Przygotuj prompt do zadania, które kończy się planem użycia AI w pracy.','Uczestnik ma wyjść z konkretnym pomysłem.','Efekt musi być indywidualny i praktyczny.','Przygotuj ćwiczenie końcowe: każdy uczestnik wybiera jedno zadanie ze swojej pracy i tworzy prompt do jego wykonania.','ćwiczenie wdrożeniowe','Zapytaj, kto wykorzysta prompt po szkoleniu.']
],
visual:[
['Ćwiczenie: Zamień tekst w schemat','Przygotujcie opis do wizualizacji','Wybierz proces i przygotuj prompt do schematu lub mapy myśli.','Nazwij proces, kroki, decyzje, osoby i efekt końcowy.','Opis ma być krótki i logiczny.','Zamień poniższy opis procesu w prosty schemat krok po kroku. Wskaż etapy, osoby odpowiedzialne, decyzje i efekt końcowy.','opis do wizualizacji','Omówcie, czy schemat pokazuje proces.'],
['Ćwiczenie: Zamień tekst w schemat','Schemat organizacji szkolenia','Przygotuj prompt do wizualizacji procesu organizacji szkolenia.','Wypisz etapy od planowania do ewaluacji.','Schemat powinien pomóc zrozumieć kolejność działań.','Zamień opis organizacji szkolenia w schemat etapów: planowanie, rekrutacja, materiały, realizacja, ewaluacja, podsumowanie.','schemat procesu','Sprawdźcie, czy nie brakuje ważnego etapu.'],
['Ćwiczenie: Zamień tekst w schemat','Mapa narzędzi AI','Przygotuj prompt do mapy narzędzi AI według zastosowań.','Pogrupuj narzędzia według funkcji.','Mapa ma być czytelna dla początkujących.','Utwórz mapę narzędzi AI według kategorii: tekst, dokumenty, grafika, audio, wideo, automatyzacja, wyszukiwanie.','mapa narzędzi','Omówcie, czy kategorie są logiczne.'],
['Ćwiczenie: Zamień tekst w schemat','Schemat decyzyjny','Przygotuj prompt do diagramu decyzji: kiedy użyć AI, a kiedy nie.','Dodaj pytania tak/nie.','Schemat ma pomagać w bezpiecznym wyborze.','Przygotuj prosty schemat decyzyjny: czy mogę użyć AI do tego zadania? Uwzględnij dane osobowe, poufność, potrzebę weryfikacji i odpowiedzialność człowieka.','schemat decyzyjny','To dobre ćwiczenie do zasad bezpieczeństwa.'],
['Ćwiczenie: Zamień tekst w schemat','Mapa procesu rekrutacji','Przygotuj prompt do procesu rekrutacji na szkolenie.','Wskaż kroki, dokumenty i decyzje.','Schemat powinien porządkować procedurę.','Zamień opis rekrutacji uczestników na szkolenie w schemat procesu z etapami, decyzjami i rezultatami.','schemat rekrutacji','Sprawdźcie, czy schemat jest zgodny z praktyką.'],
['Ćwiczenie: Zamień tekst w schemat','Infografika z zasadami','Przygotuj prompt do infografiki z zasadami korzystania z AI.','Zasady mają być krótkie i zrozumiałe.','Infografika powinna mieć mało tekstu.','Przygotuj strukturę infografiki „5 zasad bezpiecznego korzystania z AI w pracy”. Użyj krótkich haseł i opisów po jednym zdaniu.','struktura infografiki','Omówcie, jak skracać tekst do grafiki.']
],
forms:[
['Ćwiczenie: Przygotuj ankietę','Przygotujcie ankietę po szkoleniu','Przygotuj prompt, który pomoże stworzyć ankietę ewaluacyjną po szkoleniu.','Podaj temat, pytania, skalę ocen i pytania otwarte.','Dobry prompt może poprosić też o kod formularza.','Przygotuj kod Google Apps Script, który automatycznie utworzy formularz Google Forms do ewaluacji szkolenia. Formularz ma zawierać imię i nazwisko, 8 pytań w skali 1-5 i 3 pytania otwarte.','prompt do ankiety','To moment „wow”: nie tylko pytania, ale formularz.'],
['Ćwiczenie: Przygotuj ankietę','Ankieta po warsztacie','Przygotuj prompt do ankiety po warsztacie z AI.','Uwzględnij ocenę przydatności, ćwiczeń i prowadzenia.','Pytania powinny dać dane do poprawy szkolenia.','Przygotuj ankietę ewaluacyjną po warsztacie z AI: 6 pytań w skali 1-5 i 3 pytania otwarte.','ankieta warsztatowa','Omówcie, czy pytania naprawdę coś mierzą.'],
['Ćwiczenie: Przygotuj ankietę','Ankieta potrzeb szkoleniowych','Przygotuj prompt do badania potrzeb przed szkoleniem.','Pytania mają sprawdzić poziom i oczekiwania.','Ankieta pomaga dopasować szkolenie.','Przygotuj formularz badania potrzeb przed szkoleniem z AI. Uwzględnij doświadczenie uczestników, oczekiwania, obawy i preferowane ćwiczenia.','ankieta potrzeb','Sprawdźcie, czy pytania nie są zbyt ogólne.'],
['Ćwiczenie: Przygotuj ankietę','Ankieta satysfakcji','Przygotuj prompt do krótkiej ankiety satysfakcji.','Ma być szybko do wypełnienia.','Mniej pytań może dać więcej odpowiedzi.','Przygotuj krótką ankietę satysfakcji po szkoleniu: 5 pytań zamkniętych i 2 otwarte.','krótka ankieta','Omówcie, ile pytań to za dużo.'],
['Ćwiczenie: Przygotuj ankietę','Ankieta z testem','Przygotuj prompt do formularza łączącego ewaluację i test.','Oddziel ocenę szkolenia od wiedzy.','Respondent musi rozumieć, co ocenia.','Przygotuj strukturę formularza Google: część 1 - test wiedzy, część 2 - ankieta ewaluacyjna. Podaj typy pytań.','formularz łączony','Omówcie, czy łączenie testu i ankiety ma sens.'],
['Ćwiczenie: Przygotuj ankietę','Ankieta przez Apps Script','Przygotuj prompt, który generuje kod tworzący formularz.','Dodaj wymagane pola, typy pytań i instrukcję uruchomienia.','Kod powinien tworzyć formularz i pokazać link.','Napisz kod Google Apps Script tworzący formularz ewaluacyjny po szkoleniu. Dodaj tytuł, opis, pytania wymagane, pytania w skali 1-5 i pytania otwarte. Pokaż link w logach.','kod formularza','Pokaż różnicę między listą pytań a automatyzacją.']
],
meeting:[
['Ćwiczenie: Uporządkuj notatkę','Uporządkujcie notatkę','Notatka: „Szkolenie AI 13 czerwca. Trzeba salę, projektor, listę obecności, QR do testu. Anna sprawdza salę. Łukasz materiały. Nie wiadomo, kto wyśle przypomnienie. Ankieta po szkoleniu. Certyfikaty później.”','Dodaj zakaz dopisywania informacji, których nie ma w notatkach.','Dobry wynik oddziela fakty od braków.','Uporządkuj poniższe notatki. Przygotuj podsumowanie, listę ustaleń, tabelę zadań i listę spraw do doprecyzowania.','notatka i tabela','Podkreśl różnicę między porządkowaniem a dopowiadaniem.'],
['Ćwiczenie: Uporządkuj notatkę','Lista zadań po naradzie','Notatka: „Materiały do piątku. Formularz rejestracyjny trzeba poprawić. Nie działa link do prezentacji. Ktoś ma sprawdzić salę. Trzeba dać komunikat na stronę.”','Wskaż pola tabeli: zadanie, właściciel, termin, status.','Nie wolno wymyślać właścicieli.','Z notatek ze spotkania przygotuj tabelę zadań: zadanie, osoba odpowiedzialna, termin, status i brakujące informacje.','tabela zadań','Omówcie, jak oznaczać braki.'],
['Ćwiczenie: Uporządkuj notatkę','Podsumowanie dla kierownika','Notatka: „Było spotkanie o szkoleniu. Są problemy z terminem sali. Materiały są prawie gotowe. Trzeba potwierdzić uczestników. Ankieta jeszcze niegotowa. Decyzja o druku materiałów jutro.”','Ma być krótko i decyzyjnie.','Podsumowanie powinno wskazywać ryzyka.','Przygotuj 5-punktowe podsumowanie spotkania dla kierownika: decyzje, zadania, ryzyka, terminy i sprawy do decyzji.','podsumowanie','Sprawdźcie, czy jest dość konkretne.'],
['Ćwiczenie: Uporządkuj notatkę','Mail po spotkaniu','Notatka: „Ustalono, że szkolenie zostaje w czwartek. Materiały wyśle Łukasz. Sala 203 do potwierdzenia. Lista obecności po stronie sekretariatu. Test po szkoleniu przez QR.”','Uwzględnij decyzje i odpowiedzialności.','Mail ma utrwalać ustalenia.','Przygotuj krótki mail po spotkaniu. Uwzględnij decyzje, zadania, terminy i prośbę o potwierdzenie ustaleń.','mail po spotkaniu','Omówcie, kiedy taki mail jest potrzebny.'],
['Ćwiczenie: Uporządkuj notatkę','Ryzyka po spotkaniu','Notatka: „Dużo osób nie potwierdziło udziału. Nie wiadomo, czy będzie projektor. Link do materiałów działa tylko dla części osób. Prowadzący prosi o listę do jutra.”','Szukaj spraw bez właściciela i terminu.','Ryzyka powinny prowadzić do działań.','Przeanalizuj notatki ze spotkania i wskaż ryzyka, niejasności, decyzje odłożone oraz pytania na kolejne spotkanie.','analiza ryzyk','Wskażcie, co trzeba wyjaśnić.'],
['Ćwiczenie: Uporządkuj notatkę','Plan działań','Notatka: „Trzeba przygotować test, QR, ankietę, listę obecności, mail do uczestników, krótką instrukcję do materiałów i potwierdzić salę. Termin szkolenia za tydzień.”','Zadania mają być uporządkowane według priorytetów.','Plan ma być wykonalny.','Na podstawie notatek przygotuj plan działań na najbliższy tydzień: priorytet, zadanie, termin, osoba, ryzyko opóźnienia.','plan działań','Omówcie, czy priorytety są uzasadnione.']
],
email:[
['Ćwiczenie: Odpowiedz na trudnego maila','Przygotujcie odpowiedź','Mail: „Dzień dobry, nie rozumiem, dlaczego nie dostałem informacji o szkoleniu wcześniej. Uważam, że zasady rekrutacji są niejasne, a formularz był mało czytelny. Proszę o pilne wyjaśnienie tej sytuacji.”','Nie przyznawaj racji ani winy, jeśli nie wynika to z treści. Poproś o doprecyzowanie i zapowiedz weryfikację.','Odpowiedź ma być spokojna, konkretna i bezpieczna.','Przygotuj uprzejmą odpowiedź na poniższą wiadomość. Ton ma być spokojny i rzeczowy. Nie przyznawaj racji ani winy, jeśli nie wynika to z treści.','odpowiedź mailowa','Omówcie, co obniża napięcie w komunikacji.'],
['Ćwiczenie: Odpowiedz na trudnego maila','Odpowiedź na skargę','Mail: „To szkolenie było źle zorganizowane. Nikt nie wiedział, gdzie są materiały, a prowadzący za szybko omawiał tematy. Proszę o informację, kto odpowiada za organizację.”','Ton ma być spokojny i rzeczowy.','Nie wolno obiecywać czegoś bez weryfikacji.','Przygotuj odpowiedź na skargę dotyczącą organizacji szkolenia. Podziękuj za zgłoszenie, poinformuj o weryfikacji i poproś o brakujące dane.','odpowiedź na skargę','Omówcie bezpieczne sformułowania.'],
['Ćwiczenie: Odpowiedz na trudnego maila','Odpowiedź na niejasne pytanie','Mail: „Proszę mi powiedzieć, dlaczego moje zgłoszenie nie zostało uwzględnione. Nie dostałem żadnej informacji i oczekuję odpowiedzi dzisiaj.”','Poproś o doprecyzowanie i nie zgaduj.','Odpowiedź nie może dopowiadać faktów.','Przygotuj odpowiedź na niejasne pytanie. Uprzejmie poproś o doprecyzowanie i wskaż, jakie informacje są potrzebne do udzielenia odpowiedzi.','doprecyzowanie','Pokaż, że pytanie zwrotne bywa najlepszą odpowiedzią.'],
['Ćwiczenie: Odpowiedz na trudnego maila','Odpowiedź odmowna','Mail: „Proszę dopisać mnie do listy uczestników, mimo że termin rekrutacji już minął. Uważam, że powinienem mieć możliwość udziału.”','Odmowa ma być jasna i uprzejma.','Nie należy pisać zbyt defensywnie.','Przygotuj uprzejmą odpowiedź odmowną. Wyjaśnij decyzję prostym językiem, zachowaj profesjonalny ton i wskaż możliwe dalsze kroki, jeśli są dostępne.','odmowa','Omówcie, jak odmówić bez eskalacji.'],
['Ćwiczenie: Odpowiedz na trudnego maila','Odpowiedź przypominająca','Mail: „Nie mam czasu na wypełnianie kolejnych formularzy. Wszystkie dane już Państwo mają. Proszę nie wysyłać mi ponagleń.”','Ton ma być stanowczy, ale uprzejmy.','Przypomnienie nie powinno brzmieć oskarżająco.','Przygotuj uprzejme przypomnienie o konieczności przesłania brakujących informacji. Styl profesjonalny, krótki i konkretny.','przypomnienie','Omówcie, jak pisać stanowczo bez agresji.'],
['Ćwiczenie: Odpowiedz na trudnego maila','Odpowiedź do uczestnika','Mail: „Nie mogę znaleźć materiałów. Link nie działa albo nie mam dostępu. Przez to nie mogę przygotować się do szkolenia.”','Pomóż, ale nie zakładaj winy po żadnej stronie.','Odpowiedź ma być praktyczna.','Przygotuj odpowiedź do uczestnika, który nie może znaleźć materiałów szkoleniowych. Podaj spokojne instrukcje i zaproponuj kontakt w razie dalszego problemu.','pomoc techniczna','Omówcie, czy odpowiedź jest wystarczająco konkretna.']
]
};

let currentExerciseType='prompt';
function esc(s){return String(s).replace(/[&<>'"]/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m];});}
function init(){
  var toolContainer=document.getElementById('toolCards');
  if(toolContainer){
    toolContainer.innerHTML=tools.map(function(t){
      return '<article class="card"><span class="tag">'+esc(t[0])+'</span><h3>'+esc(t[1])+'</h3><p>'+esc(t[2])+'</p><a class="btn" target="_blank" href="'+esc(t[3])+'">Otwórz</a></article>';
    }).join('');
  }
}
function pickExercise(type){var list=exercises[type]||exercises.prompt;return list[Math.floor(Math.random()*list.length)];}
function renderExercise(e){
  document.getElementById('exTitle').textContent=e[0];
  document.getElementById('exHeading').textContent=e[1];
  document.getElementById('exTask').textContent=e[2];
  document.getElementById('exHint').textContent=e[3];
  document.getElementById('exCheck').textContent=e[4];
  document.getElementById('exSample').textContent=e[5];
  document.getElementById('exResult').textContent=e[6];
  document.getElementById('exDiscuss').textContent=e[7]||'Porównajcie wynik pracy z przykładem i wskażcie, co można poprawić.';
  ['exHint','exCheck','exSample','exDiscuss'].forEach(function(id){document.getElementById(id).classList.remove('active');});
  document.getElementById('exWork').value='';
}
function openExercise(type){currentExerciseType=type;renderExercise(pickExercise(type));document.getElementById('exerciseOverlay').classList.add('active');}
function randomizeCurrentExercise(){renderExercise(pickExercise(currentExerciseType));}
function closeExercise(){document.getElementById('exerciseOverlay').classList.remove('active');}
function toggle(id){document.getElementById(id).classList.toggle('active');}
function qrGenerate(){
  var v=document.getElementById('qrInput').value.trim();
  if(!v){alert('Wklej link.');return;}
  try{new URL(v);}catch(e){alert('Wklej poprawny link zaczynający się od https:// albo http://');return;}
  var src='https://api.qrserver.com/v1/create-qr-code/?size=360x360&data='+encodeURIComponent(v);
  document.getElementById('qrBox').innerHTML='<img src="'+src+'" alt="QR">';
  document.getElementById('qrText').textContent=v;
}
function qrClear(){document.getElementById('qrInput').value='';document.getElementById('qrBox').textContent='Tutaj pojawi się kod QR';document.getElementById('qrText').textContent='';}
function qrBig(){
  var v=document.getElementById('qrInput').value.trim();
  if(!v){alert('Najpierw wklej link i wygeneruj QR.');return;}
  try{new URL(v);}catch(e){alert('Wklej poprawny link zaczynający się od https:// albo http://');return;}
  var src='https://api.qrserver.com/v1/create-qr-code/?size=900x900&data='+encodeURIComponent(v);
  document.getElementById('qrFullImg').innerHTML='<img src="'+src+'" alt="QR">';
  document.getElementById('qrFullText').textContent=v;
  document.getElementById('qrFull').classList.add('active');
}
function closeQrBig(){document.getElementById('qrFull').classList.remove('active');}
document.addEventListener('keydown',function(e){if(e.key==='Escape'){closeExercise();closeQrBig();}});
init();
